import "@/styles/globals.css";
import { ChakraProvider, Container } from "@chakra-ui/react";
import Head from "next/head";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider>
        <Container
          className={roboto.className}
          py={"4"}
          maxW="container.lg"
          // border="1px solid black"
        >
          <Component {...pageProps} />
        </Container>
      </ChakraProvider>
    </>
  );
}
